[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  CI = "false"
  DISABLE_ESLINT_PLUGIN = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 