[build]
builder = "python"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/api/search/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[service]
sourceDirectory = "backend"

[variables]
NIXPACKS_PYTHON_VERSION = "3.12.0"
