- type: static
  name: torre-frontend
  env: node
  buildCommand: npm install && npm run build
  staticPublishPath: ./build
  envVars:
    - key: NODE_VERSION
      value: 20.x
    - key: NODE_ENV
      value: production
    - key: CI
      value: false
    - key: DISABLE_ESLINT_PLUGIN
      value: true
