services:
  - type: web
    name: torre-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0

  - type: static
    name: torre-frontend
    env: node
    buildCommand: |
      npm cache clean --force
      rm -rf node_modules
      npm install
      npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: NODE_ENV
        value: production
      - key: CI
        value: false
      - key: DISABLE_ESLINT_PLUGIN
        value: true 