services:
  - type: web
    name: torre-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0

  - type: static
    name: torre-frontend
    env: node
    buildCommand: |
      npm ci
      npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production 