[phases.setup]
nixPkgs = ["python312"]
aptPkgs = ["python3-pip", "python3-dev", "build-essential"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT" 